# Generated by Django 2.0.2 on 2018-05-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_app', '0004_auto_20180524_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_model',
            name='feedback',
            field=models.CharField(default=0, max_length=264),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback_model',
            name='name',
            field=models.CharField(max_length=264, unique=True),
        ),
    ]
