# Generated by Django 2.0.2 on 2018-05-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_app', '0006_archery_board'),
    ]

    operations = [
        migrations.DeleteModel(
            name='archery_board',
        ),
    ]
